import { promises as fs } from 'node:fs';
import path from 'node:path';
import type { SourceKind } from './types.js';
const supported = new Map<string, SourceKind>([['.json', 'json'], ['.jsonl', 'jsonl'], ['.md', 'markdown'], ['.markdown', 'markdown'], ['.txt', 'text']]);
export function sourceKind(filePath: string): SourceKind | undefined { return supported.get(path.extname(filePath).toLowerCase()); }
function globRegex(pattern: string): RegExp { let body = ''; for (let index = 0; index < pattern.length; index += 1) { const character = pattern[index]!; if (character === '*') { if (pattern[index + 1] === '*') { body += '.*'; index += 1; } else body += '[^/]*'; } else if (character === '?') body += '[^/]'; else body += character.replace(/[|\\{}()[\]^$+?.]/g, '\\$&'); } return new RegExp(`^${body}$`); }
function matchesInclude(relativePath: string, patterns: readonly string[]): boolean { return patterns.some((pattern) => { const normalized = pattern.split(path.sep).join('/').replace(/^\.\//, ''); const candidate = normalized.includes('/') ? relativePath : path.posix.basename(relativePath); return globRegex(normalized).test(candidate); }); }
export async function listSourceFiles(root: string, excludedDirectories: readonly string[] = [], include?: readonly string[]): Promise<string[]> { const stat = await fs.stat(root); const accepted = (filePath: string): boolean => { if (!sourceKind(filePath)) return false; if (include === undefined) return true; const relative = stat.isFile() ? path.basename(filePath) : normalizeRelative(root, filePath); return matchesInclude(relative, include); }; if (stat.isFile()) return accepted(root) ? [path.resolve(root)] : []; const excluded = new Set(excludedDirectories.map((dir) => path.resolve(dir))); const found: string[] = []; async function walk(dir: string): Promise<void> { if (excluded.has(path.resolve(dir))) return; const entries = await fs.readdir(dir, { withFileTypes: true }); entries.sort((a, b) => a.name.localeCompare(b.name)); for (const entry of entries) { if (entry.name.startsWith('.') || entry.name === 'node_modules') continue; const full = path.join(dir, entry.name); if (entry.isDirectory()) await walk(full); else if (entry.isFile() && accepted(full)) found.push(path.resolve(full)); } } await walk(root); return found; }
export async function ensureDir(dir: string): Promise<void> { await fs.mkdir(dir, { recursive: true }); }
export function normalizeRelative(root: string, file: string): string { const relative = path.relative(path.resolve(root), path.resolve(file)).split(path.sep).join('/'); return relative || path.basename(file); }
