import { promises as fs } from 'node:fs';
import path from 'node:path';
import { ensureDir, listSourceFiles, normalizeRelative, sourceKind } from './fs.js';
import { sha256 } from './hash.js';
import { topKeywords } from './keywords.js';
import { parseSource } from './parse.js';
import type { Chunk, InspectOptions, Manifest, SourceFile } from './types.js';
export async function inspect(options: InspectOptions): Promise<Manifest> { const root = path.resolve(options.input); const maxChunkLines = options.maxChunkLines ?? 80; const maxChunkChars = options.maxChunkChars ?? 4000; const files = await listSourceFiles(root); const sources: SourceFile[] = []; const chunks: Chunk[] = []; for (const filePath of files) { const kind = sourceKind(filePath); if (!kind) continue; const body = await fs.readFile(filePath, 'utf8'); const relativePath = normalizeRelative(root, filePath); const sourceId = `src-${String(sources.length + 1).padStart(4, '0')}`; const source: SourceFile = { id: sourceId, path: filePath, relativePath, kind, bytes: Buffer.byteLength(body), sha256: sha256(body) }; sources.push(source); for (const span of parseSource(body, kind, maxChunkLines, maxChunkChars)) { const id = `chunk-${String(chunks.length + 1).padStart(4, '0')}`; chunks.push({ id, sourceId, sourcePath: relativePath, kind, ...(span.role ? { role: span.role } : {}), ...(span.createdAt ? { createdAt: span.createdAt } : {}), text: span.text, sha256: sha256(span.text), citation: { sourceId, sourcePath: relativePath, startLine: span.startLine, endLine: span.endLine, startOffset: span.startOffset, endOffset: span.endOffset }, keywords: topKeywords(span.text) }); } } const manifest: Manifest = { version: 1, generatedAt: new Date(0).toISOString(), inputRoot: root, sources, chunks, stats: { sourceCount: sources.length, chunkCount: chunks.length, totalBytes: sources.reduce((sum, source) => sum + source.bytes, 0), totalTextChars: chunks.reduce((sum, chunk) => sum + chunk.text.length, 0) } }; if (options.output) await writeManifest(manifest, options.output); return manifest; }
export async function writeManifest(manifest: Manifest, outputDir: string): Promise<void> { await ensureDir(outputDir); await fs.writeFile(path.join(outputDir, 'manifest.json'), `${JSON.stringify(manifest, null, 2)}\n`, 'utf8'); await fs.writeFile(path.join(outputDir, 'manifest.md'), renderManifestMarkdown(manifest), 'utf8'); }
export function renderManifestMarkdown(manifest: Manifest): string { const rows = manifest.chunks.map((chunk) => `| ${chunk.id} | ${chunk.sourcePath}:${chunk.citation.startLine}-${chunk.citation.endLine} | ${chunk.role ?? ''} | ${chunk.keywords.slice(0, 5).join(', ')} |`); return ['# contextloom manifest', '', `Sources: ${manifest.stats.sourceCount}`, `Chunks: ${manifest.stats.chunkCount}`, `Bytes: ${manifest.stats.totalBytes}`, '', '| Chunk | Citation | Role | Keywords |', '| --- | --- | --- | --- |', ...rows, ''].join('\n'); }
