import type { LineSpan } from './lines.js';
import { lineStarts, offsetToLine, splitLineSpans } from './lines.js';
import type { SourceKind } from './types.js';
export interface ParsedSpan extends LineSpan { readonly role?: string; readonly createdAt?: string; }
interface JsonMessage { role?: unknown; content?: unknown; text?: unknown; message?: unknown; createdAt?: unknown; timestamp?: unknown; }
function textFromMessage(value: JsonMessage): string | undefined { const candidate = value.content ?? value.text ?? value.message; if (typeof candidate === 'string') return candidate; if (Array.isArray(candidate)) return candidate.map((item) => typeof item === 'string' ? item : JSON.stringify(item)).join('\n'); if (candidate && typeof candidate === 'object') return JSON.stringify(candidate, null, 2); return undefined; }
function findMessages(value: unknown): JsonMessage[] { if (Array.isArray(value)) return value.flatMap(findMessages); if (!value || typeof value !== 'object') return []; const record = value as Record<string, unknown>; for (const key of ['messages', 'turns', 'events', 'transcript']) if (Array.isArray(record[key])) return findMessages(record[key]); if ('content' in record || 'text' in record || 'message' in record) return [record as JsonMessage]; return []; }
export function parseSource(text: string, kind: SourceKind, maxLines: number, maxChars: number): ParsedSpan[] { if (kind === 'json') return parseJson(text, maxLines, maxChars); if (kind === 'jsonl') return parseJsonl(text, maxLines, maxChars); return splitLineSpans(text, maxLines, maxChars); }
interface JsonStringRange { readonly startOffset: number; readonly endOffset: number; readonly boundaries: readonly number[]; }
function findJsonString(text: string, value: string, searchFrom: number): JsonStringRange | undefined { for (let keyStart = text.indexOf('"', searchFrom); keyStart >= 0; keyStart = text.indexOf('"', keyStart + 1)) { let keyEnd = keyStart + 1; while (keyEnd < text.length && text[keyEnd] !== '"') { if (text[keyEnd] === '\\') keyEnd += 1; keyEnd += 1; } if (keyEnd >= text.length) return undefined; let key: unknown; try { key = JSON.parse(text.slice(keyStart, keyEnd + 1)); } catch { keyStart = keyEnd; continue; } if (!['content', 'text', 'message'].includes(String(key))) { keyStart = keyEnd; continue; } let start = keyEnd + 1; while (/\s/u.test(text[start] ?? '')) start += 1; if (text[start] !== ':') { keyStart = keyEnd; continue; } start += 1; while (/\s/u.test(text[start] ?? '')) start += 1; if (text[start] !== '"') { keyStart = keyEnd; continue; } let end = start + 1; while (end < text.length && text[end] !== '"') { if (text[end] === '\\') end += 1; end += 1; } if (end >= text.length) return undefined; let decoded: unknown; try { decoded = JSON.parse(text.slice(start, end + 1)); } catch { keyStart = end; continue; } if (decoded !== value) { keyStart = end; continue; } const boundaries = [start + 1]; for (let index = start + 1; index < end;) { if (text[index] === '\\') { if (text[index + 1] === 'u') index += 6; else index += 2; } else index += 1; boundaries.push(index); } if (boundaries.length === value.length + 1) return { startOffset: start + 1, endOffset: end, boundaries }; keyStart = end; } return undefined; }
function parseJson(text: string, maxLines: number, maxChars: number): ParsedSpan[] { try { const messages = findMessages(JSON.parse(text)); if (messages.length === 0) return splitLineSpans(text, maxLines, maxChars); const starts = lineStarts(text); let searchFrom = 0; return messages.flatMap((message) => { const content = textFromMessage(message); if (!content?.trim()) return []; const range = findJsonString(text, content, searchFrom); if (!range) return []; searchFrom = range.endOffset + 1; return splitLineSpans(content, maxLines, maxChars).map((span) => { const startOffset = range.boundaries[span.startOffset] ?? range.startOffset; const endOffset = range.boundaries[span.endOffset] ?? range.endOffset; return { ...span, startLine: offsetToLine(starts, startOffset), endLine: offsetToLine(starts, Math.max(startOffset, endOffset - 1)), startOffset, endOffset, ...(typeof message.role === 'string' ? { role: message.role } : {}), ...(typeof message.createdAt === 'string' ? { createdAt: message.createdAt } : typeof message.timestamp === 'string' ? { createdAt: message.timestamp } : {}) }; }); }); } catch { return splitLineSpans(text, maxLines, maxChars); } }
function parseJsonl(text: string, maxLines: number, maxChars: number): ParsedSpan[] { const starts = lineStarts(text); const spans: ParsedSpan[] = []; let offset = 0; for (const line of text.split(/(?<=\n)/u)) { const trimmed = line.trim(); if (trimmed) { try { const parsed = JSON.parse(trimmed) as JsonMessage; const content = textFromMessage(parsed) ?? trimmed; for (const span of splitLineSpans(content, maxLines, maxChars)) spans.push({ ...span, startLine: offsetToLine(starts, offset), endLine: offsetToLine(starts, Math.max(offset, offset + line.length - 1)), startOffset: offset, endOffset: offset + line.length, ...(typeof parsed.role === 'string' ? { role: parsed.role } : {}), ...(typeof parsed.createdAt === 'string' ? { createdAt: parsed.createdAt } : typeof parsed.timestamp === 'string' ? { createdAt: parsed.timestamp } : {}) }); } catch { spans.push(...splitLineSpans(trimmed, maxLines, maxChars).map((span) => ({ ...span, startOffset: offset, endOffset: offset + line.length }))); } } offset += line.length; } return spans; }
