import type { LineSpan } from './lines.js';
import { lineStarts, offsetToLine, splitLineSpans } from './lines.js';
import type { SourceKind } from './types.js';
export interface ParsedSpan extends LineSpan { readonly role?: string; readonly createdAt?: string; }
interface JsonMessage { role?: unknown; content?: unknown; text?: unknown; message?: unknown; createdAt?: unknown; timestamp?: unknown; }
function textFromMessage(value: JsonMessage): string | undefined { const candidate = value.content ?? value.text ?? value.message; if (typeof candidate === 'string') return candidate; if (Array.isArray(candidate)) return candidate.map((item) => typeof item === 'string' ? item : JSON.stringify(item)).join('\n'); if (candidate && typeof candidate === 'object') return JSON.stringify(candidate, null, 2); return undefined; }
function findMessages(value: unknown): JsonMessage[] { if (Array.isArray(value)) return value.flatMap(findMessages); if (!value || typeof value !== 'object') return []; const record = value as Record<string, unknown>; for (const key of ['messages', 'turns', 'events', 'transcript']) if (Array.isArray(record[key])) return findMessages(record[key]); if ('content' in record || 'text' in record || 'message' in record) return [record as JsonMessage]; return []; }
export function parseSource(text: string, kind: SourceKind, maxLines: number, maxChars: number): ParsedSpan[] { if (kind === 'json') return parseJson(text, maxLines, maxChars); if (kind === 'jsonl') return parseJsonl(text, maxLines, maxChars); return splitLineSpans(text, maxLines, maxChars); }
interface JsonValueRange { readonly startOffset: number; readonly endOffset: number; readonly boundaries?: readonly number[]; }
function jsonValueEnd(text: string, start: number): number | undefined { const opener = text[start]; if (opener === '"') { let index = start + 1; while (index < text.length) { if (text[index] === '\\') index += 2; else if (text[index] === '"') return index + 1; else index += 1; } return undefined; } if (opener !== '[' && opener !== '{') return undefined; const stack = [opener]; let inString = false; for (let index = start + 1; index < text.length; index += 1) { const char = text[index]; if (inString) { if (char === '\\') index += 1; else if (char === '"') inString = false; continue; } if (char === '"') inString = true; else if (char === '[' || char === '{') stack.push(char); else if (char === ']' || char === '}') { const expected = char === ']' ? '[' : '{'; if (stack.pop() !== expected) return undefined; if (stack.length === 0) return index + 1; } } return undefined; }
function findJsonValue(text: string, value: string, searchFrom: number): JsonValueRange | undefined { const candidates = ['content', 'text', 'message'].flatMap((key) => { const token = JSON.stringify(key); const offsets: number[] = []; for (let index = text.indexOf(token, searchFrom); index >= 0; index = text.indexOf(token, index + token.length)) offsets.push(index); return offsets; }).sort((a, b) => a - b); for (const keyStart of candidates) { const keyEnd = jsonValueEnd(text, keyStart)!; let start = keyEnd; while (/\s/u.test(text[start] ?? '')) start += 1; if (text[start] !== ':') continue; start += 1; while (/\s/u.test(text[start] ?? '')) start += 1; const end = jsonValueEnd(text, start); if (!end) continue; let decoded: unknown; try { decoded = JSON.parse(text.slice(start, end)); } catch { continue; } if (textFromMessage({ content: decoded }) !== value) continue; if (typeof decoded !== 'string') return { startOffset: start, endOffset: end }; const boundaries = [start + 1]; for (let index = start + 1; index < end - 1;) { if (text[index] === '\\') { if (text[index + 1] === 'u') index += 6; else index += 2; } else index += 1; boundaries.push(index); } if (boundaries.length === decoded.length + 1) return { startOffset: start + 1, endOffset: end - 1, boundaries }; } return undefined; }
function parseJson(text: string, maxLines: number, maxChars: number): ParsedSpan[] { try { const messages = findMessages(JSON.parse(text)); if (messages.length === 0) return splitLineSpans(text, maxLines, maxChars); const starts = lineStarts(text); let searchFrom = 0; return messages.flatMap((message) => { const content = textFromMessage(message); if (!content?.trim()) return []; const range = findJsonValue(text, content, searchFrom); if (!range) return []; searchFrom = range.endOffset; return splitLineSpans(content, maxLines, maxChars).map((span) => { const startOffset = range.boundaries?.[span.startOffset] ?? range.startOffset; const endOffset = range.boundaries?.[span.endOffset] ?? range.endOffset; return { ...span, startLine: offsetToLine(starts, startOffset), endLine: offsetToLine(starts, Math.max(startOffset, endOffset - 1)), startOffset, endOffset, ...(typeof message.role === 'string' ? { role: message.role } : {}), ...(typeof message.createdAt === 'string' ? { createdAt: message.createdAt } : typeof message.timestamp === 'string' ? { createdAt: message.timestamp } : {}) }; }); }); } catch { return splitLineSpans(text, maxLines, maxChars); } }
function parseJsonl(text: string, maxLines: number, maxChars: number): ParsedSpan[] { const starts = lineStarts(text); const spans: ParsedSpan[] = []; let offset = 0; for (const line of text.split(/(?<=\n)/u)) { const trimmed = line.trim(); if (trimmed) { try { const parsed = JSON.parse(trimmed) as JsonMessage; const content = textFromMessage(parsed) ?? trimmed; const range = findJsonValue(line, content, 0); for (const span of splitLineSpans(content, maxLines, maxChars)) { const startOffset = offset + (range?.boundaries?.[span.startOffset] ?? range?.startOffset ?? 0); const endOffset = offset + (range?.boundaries?.[span.endOffset] ?? range?.endOffset ?? line.length); spans.push({ ...span, startLine: offsetToLine(starts, startOffset), endLine: offsetToLine(starts, Math.max(startOffset, endOffset - 1)), startOffset, endOffset, ...(typeof parsed.role === 'string' ? { role: parsed.role } : {}), ...(typeof parsed.createdAt === 'string' ? { createdAt: parsed.createdAt } : typeof parsed.timestamp === 'string' ? { createdAt: parsed.timestamp } : {}) }); } } catch { spans.push(...splitLineSpans(trimmed, maxLines, maxChars).map((span) => ({ ...span, startOffset: offset, endOffset: offset + line.length }))); } } offset += line.length; } return spans; }
