import type { LineSpan } from './lines.js';
import { lineStarts, offsetToLine, splitLineSpans } from './lines.js';
import type { SourceKind } from './types.js';
export interface ParsedSpan extends LineSpan { readonly role?: string; readonly createdAt?: string; }
interface JsonMessage { role?: unknown; content?: unknown; text?: unknown; message?: unknown; createdAt?: unknown; timestamp?: unknown; }
function textFromMessage(value: JsonMessage): string | undefined { const candidate = value.content ?? value.text ?? value.message; if (typeof candidate === 'string') return candidate; if (Array.isArray(candidate)) return candidate.map((item) => typeof item === 'string' ? item : JSON.stringify(item)).join('\n'); if (candidate && typeof candidate === 'object') return JSON.stringify(candidate, null, 2); return undefined; }
function findMessages(value: unknown): JsonMessage[] { if (Array.isArray(value)) return value.flatMap(findMessages); if (!value || typeof value !== 'object') return []; const record = value as Record<string, unknown>; for (const key of ['messages', 'turns', 'events', 'transcript']) if (Array.isArray(record[key])) return findMessages(record[key]); if ('content' in record || 'text' in record || 'message' in record) return [record as JsonMessage]; return []; }
export function parseSource(text: string, kind: SourceKind, maxLines: number, maxChars: number): ParsedSpan[] { if (kind === 'json') return parseJson(text, maxLines, maxChars); if (kind === 'jsonl') return parseJsonl(text, maxLines, maxChars); return splitLineSpans(text, maxLines, maxChars); }
function parseJson(text: string, maxLines: number, maxChars: number): ParsedSpan[] { try { const messages = findMessages(JSON.parse(text)); if (messages.length === 0) return splitLineSpans(text, maxLines, maxChars); const starts = lineStarts(text); let searchFrom = 0; return messages.flatMap((message) => { const content = textFromMessage(message); if (!content?.trim()) return []; const rawIndex = text.indexOf(content.split('\n')[0] ?? content, searchFrom); const startOffset = rawIndex >= 0 ? rawIndex : searchFrom; const endOffset = rawIndex >= 0 ? rawIndex + content.length : Math.min(text.length, startOffset + content.length); searchFrom = endOffset; return splitLineSpans(content, maxLines, maxChars).map((span) => ({ ...span, startLine: offsetToLine(starts, startOffset), endLine: offsetToLine(starts, Math.max(startOffset, endOffset - 1)), startOffset, endOffset, ...(typeof message.role === 'string' ? { role: message.role } : {}), ...(typeof message.createdAt === 'string' ? { createdAt: message.createdAt } : typeof message.timestamp === 'string' ? { createdAt: message.timestamp } : {}) })); }); } catch { return splitLineSpans(text, maxLines, maxChars); } }
function parseJsonl(text: string, maxLines: number, maxChars: number): ParsedSpan[] { const starts = lineStarts(text); const spans: ParsedSpan[] = []; let offset = 0; for (const line of text.split(/(?<=\n)/u)) { const trimmed = line.trim(); if (trimmed) { try { const parsed = JSON.parse(trimmed) as JsonMessage; const content = textFromMessage(parsed) ?? trimmed; for (const span of splitLineSpans(content, maxLines, maxChars)) spans.push({ ...span, startLine: offsetToLine(starts, offset), endLine: offsetToLine(starts, Math.max(offset, offset + line.length - 1)), startOffset: offset, endOffset: offset + line.length, ...(typeof parsed.role === 'string' ? { role: parsed.role } : {}), ...(typeof parsed.createdAt === 'string' ? { createdAt: parsed.createdAt } : typeof parsed.timestamp === 'string' ? { createdAt: parsed.timestamp } : {}) }); } catch { spans.push(...splitLineSpans(trimmed, maxLines, maxChars).map((span) => ({ ...span, startOffset: offset, endOffset: offset + line.length }))); } } offset += line.length; } return spans; }
